//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace productmanagementsystems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buy
    {
        public int Purchase_Id { get; set; }
        public string Qtn { get; set; }
        public int Productid { get; set; }
        public int Clinetid { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual product product { get; set; }
    }
}
