//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace productmanagementsystems.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sd2Entities : DbContext
    {
        public sd2Entities()
            : base("name=sd2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminlog> Adminlogs { get; set; }
        public virtual DbSet<buy> buys { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<delivered> delivereds { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<product> products { get; set; }
    }
}
