//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace productmanagementsystems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivered
    {
        public int delever_Id { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<int> o_quantity { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual product product { get; set; }
    }
}
